"use client";

import React, { useState } from "react";
import { Cpu, Sliders, CheckCircle2, Sparkles, Activity, ShieldCheck, Zap } from "lucide-react";

export default function RulesView() {
  const [confidenceThreshold, setConfidenceThreshold] = useState(85);
  const [speedDeltaThreshold, setSpeedDeltaThreshold] = useState(30);
  const [blankingTimeout, setBlankingTimeout] = useState(3);

  const models = [
    {
      id: "m-01",
      name: "Kinematic Doppler Discrepancy Net (KDD-Net)",
      version: "v4.2.1-Prod",
      type: "Physics-Informed Deep Neural Network",
      status: "ACTIVE (INFERENCE 4.2ms)",
      accuracy: "98.9%",
      f1Score: "0.984",
      description: "Cross-checks reported NMEA vessel velocity and heading against the hydrodynamic inertia and turn constraints of specific ship deadweight tonnage classes.",
    },
    {
      id: "m-02",
      name: "Synthetic Circular Orbit Classifier (SCOC)",
      version: "v3.8.0-Prod",
      type: "Spatial-Temporal Graph Convolutional Network",
      status: "ACTIVE (INFERENCE 6.1ms)",
      accuracy: "99.4%",
      f1Score: "0.991",
      description: "Identifies classic circular GPS drift patterns (radius 0.8 nm - 2.5 nm) generated by terrestrial RF spoofing transmitters in the Arabian Sea and Gulf of Oman.",
    },
    {
      id: "m-03",
      name: "Discontinuous Coordinate Jump Filter (DCJF)",
      version: "v5.0.2-Prod",
      type: "Kalman Filter & Kinematic State Space",
      status: "ACTIVE (INFERENCE 1.1ms)",
      accuracy: "99.8%",
      f1Score: "0.997",
      description: "Instantly flags teleportation anomalies where reported geographic position shifts faster than the maximum physical speed of the vessel category.",
    },
    {
      id: "m-04",
      name: "Dark Fleet Transponder & Identity Clone Resolver",
      version: "v2.6.4-Prod",
      type: "Multi-Source Entity Resolution",
      status: "ACTIVE (INFERENCE 8.4ms)",
      accuracy: "97.6%",
      f1Score: "0.970",
      description: "Detects duplicate MMSI emissions received from separate geographic centroids and flags intentional transponder suppression during chokepoint transit.",
    },
  ];

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      {/* Banner */}
      <div className="rounded-2xl p-6 glass-card border border-cyan-500/25 shadow-md relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2.5 py-0.5 rounded-full bg-cyan-100 text-cyan-800 border border-cyan-300 text-[10px] font-mono font-bold uppercase tracking-wider flex items-center gap-1.5">
                <Cpu className="w-3.5 h-3.5 text-cyan-700" />
                NEURAL ANOMALY ENGINE & REASONING LAB
              </span>
              <span className="text-xs font-mono text-emerald-700 font-bold">
                4 MODELS IN ENSEMBLE
              </span>
            </div>
            <h2 className="text-2xl font-black text-slate-900 tracking-tight">
              AI Detection Models & Defense Rule Engine
            </h2>
            <p className="text-xs text-slate-600 mt-1 max-w-2xl leading-relaxed">
              Ensemble deep-learning architecture combining physics-informed kinematic models, spatial graph networks, and multi-constellation parity checkers to deliver sub-second anomaly identification.
            </p>
          </div>
        </div>
      </div>

      {/* Model Cards Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="space-y-4">
          <span className="text-xs font-mono uppercase tracking-wider text-slate-500 font-bold block">
            Production Detection Models
          </span>
          {models.map((model) => (
            <div key={model.id} className="p-4 rounded-xl glass-card border border-cyan-500/25 shadow-xs space-y-2 text-xs bg-white/90">
              <div className="flex items-start justify-between gap-2">
                <div>
                  <h4 className="font-bold text-slate-900 text-xs">{model.name}</h4>
                  <span className="text-[10px] font-mono text-cyan-800 font-semibold">{model.version} &bull; {model.type}</span>
                </div>
                <span className="text-[9px] font-mono font-bold text-emerald-700 bg-emerald-100 border border-emerald-300 px-2 py-0.5 rounded">
                  {model.status}
                </span>
              </div>
              <p className="text-slate-600 text-[11px] leading-relaxed">{model.description}</p>
              <div className="flex items-center justify-between text-[10px] font-mono text-slate-500 pt-2 border-t border-slate-200">
                <span>Accuracy: <strong className="text-emerald-700 font-bold">{model.accuracy}</strong></span>
                <span>F1-Score: <strong className="text-cyan-800 font-bold">{model.f1Score}</strong></span>
              </div>
            </div>
          ))}
        </div>

        {/* Real-time Threshold Tuning */}
        <div className="rounded-2xl glass-card border border-cyan-500/25 p-5 shadow-md space-y-5 h-fit bg-white/90">
          <h3 className="text-sm font-black text-slate-900 tracking-wide pb-2 border-b border-cyan-500/20 flex items-center justify-between">
            <span className="flex items-center gap-2">
              <Sliders className="w-4 h-4 text-cyan-700" />
              Autonomous Rule Engine Parameters
            </span>
            <span className="text-[10px] font-mono text-cyan-800 font-bold">REAL-TIME APPLIED</span>
          </h3>

          <div className="space-y-4 text-xs">
            {/* Slider 1 */}
            <div>
              <div className="flex items-center justify-between text-slate-800 mb-1.5 font-mono">
                <span className="font-semibold">AI Spoofing Confidence Threshold</span>
                <span className="text-cyan-800 font-black">{confidenceThreshold}%</span>
              </div>
              <input
                type="range"
                min="50"
                max="99"
                value={confidenceThreshold}
                onChange={(e) => setConfidenceThreshold(Number(e.target.value))}
                className="w-full accent-cyan-600 cursor-pointer"
              />
              <p className="text-[10px] text-slate-500 mt-1 font-medium">Alerts triggering above this threshold automatically dispatch advisories to regional port authorities.</p>
            </div>

            {/* Slider 2 */}
            <div>
              <div className="flex items-center justify-between text-slate-800 mb-1.5 font-mono">
                <span className="font-semibold">Kinematic Velocity Jump Delta Trigger</span>
                <span className="text-cyan-800 font-black">{speedDeltaThreshold} kts</span>
              </div>
              <input
                type="range"
                min="10"
                max="80"
                value={speedDeltaThreshold}
                onChange={(e) => setSpeedDeltaThreshold(Number(e.target.value))}
                className="w-full accent-cyan-600 cursor-pointer"
              />
              <p className="text-[10px] text-slate-500 mt-1 font-medium">Maximum physically allowable velocity delta within 15 seconds before triggering impossible teleportation flag.</p>
            </div>

            {/* Slider 3 */}
            <div>
              <div className="flex items-center justify-between text-slate-800 mb-1.5 font-mono">
                <span className="font-semibold">Dark Fleet AIS Blanking Timeout</span>
                <span className="text-cyan-800 font-black">{blankingTimeout} minutes</span>
              </div>
              <input
                type="range"
                min="1"
                max="15"
                value={blankingTimeout}
                onChange={(e) => setBlankingTimeout(Number(e.target.value))}
                className="w-full accent-cyan-600 cursor-pointer"
              />
              <p className="text-[10px] text-slate-500 mt-1 font-medium">Continuous signal absence in chokepoints before an active search and radar query is launched.</p>
            </div>
          </div>

          <div className="p-3 rounded-xl bg-cyan-50 border border-cyan-200 text-xs">
            <span className="text-cyan-900 font-bold flex items-center gap-1.5 mb-1">
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
              Sensor Parity Rules Enforced
            </span>
            <p className="text-slate-600 text-[11px]">
              All 4 neural models synchronize every 5 seconds against coastal radar sweeps and satellite AIS downlinks.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
